database:
  name:  postgres
  namespace: graphql-demo
  replicas: 1

workload:
  image: postgres:16
  port: 5432
  resources:
    memory: "128Mi"
    cpu: "500m"
  volumeMounts:
    one:
      name:  postgres-persistent-storage
      mountPath:  /var/lib/postgresql/data
      resources: 
        requests:
          storage: 1Gi
  storageClassName: "gp2"
env:
  DB_NAME: graphql_db
  PGDATA: /var/lib/postgresql/data/pgdata

secrets:
  DB_USER: "cG9zdGdyZXM="
  DB_PASSWORD: "cG9zdGdyZXM="