services:
  postgres:
    image: postgres:16-alpine
    container_name: graphql_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: graphql_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  my-graphql-app:
    image: ereyes2017/graphql-demo:latest
    container_name: my-graphql-app
    ports:
      - "8000:8000"
    volumes:
      - app_data:/opt/app/data
    environment:
      DB_HOST: graphql_postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432
    depends_on: [postgres]

volumes:
  postgres_data:
  app_data:
