apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.name }}-secret
  namespace: {{ .Values.database.namespace }}
type: Opaque
data:
  DB_USER: {{ .Values.secrets.DB_USER }}
  DB_PASSWORD: {{ .Values.secrets.DB_PASSWORD }}
