apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.microservice.name }}-secret
  namespace: {{ .Values.microservice.namespace }}
type: Opaque
data:
  DB_USER: {{ .Values.secrets.DB_USER }}
  DB_PASSWORD: {{ .Values.secrets.DB_PASSWORD }}
