apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.microservice.name }}-config
  namespace: {{ .Values.microservice.namespace }}
data:
  DB_HOST: {{ .Values.env.DB_HOST }}
  DB_PORT: {{ .Values.env.DB_PORT | quote }}
  DB_NAME: {{ .Values.env.DB_NAME }}