apiVersion: v1
kind: Service
metadata:
  name: graphql-demo-api
  namespace: graphql-demo
spec:
  selector:
    app.kubernetes.io/instance: graphql-demo-api
  ports:
  - port: 8000
    targetPort: 8000
